### ISSUE TITLE
Type?

### ISSUE THREAD

**Issue by VDFOREVER** [Reeliks/blaze#9]
У тебя везде usize, его лучше использовать для индексации коллекций, возможно стоит использовать u32 или u64, а то мб что например при переносе bd с 64 битного пк на 32 битный могут быть ошибки переполнения (я особо код не изучал возможно не понял за что он отвечает)

**Comment by cogdash** [comment]
Ты прав, usize меняется в зависимости от разрядности, поэтому лучше перейти на u64. Только придётся везде дописывать "as u64" 🤠

**Comment by VDFOREVER** [comment]
Я потом посмотрю, что и как

**Comment by VDFOREVER** [comment]
Всякие as тоже плохо особенно когда делаешь выравнивание большего типа к меньшему

**Comment by cogdash** [comment]
приведение к u64 должно сглаживать переполнение usize на x32, len() возвращает как раз таки usize

**Comment by VDFOREVER** [comment]
Тогда пусть будет ass
